// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"
import Dropdown from 'stimulus-dropdown'

application.register('dropdown', Dropdown)

import EditorController from "./editor_controller"
application.register("editor", EditorController)

import PostController from "./post_controller"
application.register("post", PostController)

import IconController from "./icon_controller"
application.register("icon", IconController)

import PostSettingToggleController from "./post_setting_toggle_controller"
application.register("post-setting-toggle", PostSettingToggleController)

import ToggleController from "./toggle_controller"
application.register("toggle", ToggleController)
