// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

// Import and register all TailwindCSS Components
import { Alert, Autosave, Dropdown, Modal, Tabs, Popover, Toggle, Slideover } from "tailwindcss-stimulus-components"
application.register('alert', Alert)
application.register('autosave', Autosave)
application.register('dropdown', Dropdown)
application.register('modal', Modal)
application.register('tabs', Tabs)
application.register('popover', Popover)
application.register('toggle', Toggle)
application.register('slideover', Slideover)

import EditorController from "./editor_controller"
application.register("editor", EditorController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import LanguageToggleController from "./language_toggle_controller"
application.register("language-toggle", LanguageToggleController)

import PostController from "./post_controller"
application.register("post", PostController)

import PostSettingToggleController from "./post_setting_toggle_controller"
application.register("post-setting-toggle", PostSettingToggleController)

import ToggleController from "./toggle_controller"
application.register("toggle", ToggleController)

import UserController from "./user_controller"
application.register("user", UserController)
