// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ControllerNameController from "./controller_name_controller"
application.register("controller-name", ControllerNameController)

import EditorController from "./editor_controller"
application.register("editor", EditorController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import PostController from "./post_controller"
application.register("post", PostController)

import PostSettingToggleController from "./post_setting_toggle_controller"
application.register("post-setting-toggle", PostSettingToggleController)

import ToggleController from "./toggle_controller"
application.register("toggle", ToggleController)

import UserController from "./user_controller"
application.register("user", UserController)
