local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

development:
  service: Aliyun
  access_key_id: <%= ENV.fetch('ALIYUN_ACCESS_KEY_ID') { "" } %>
  access_key_secret: <%= ENV.fetch('ALIYUN_ACCESS_KEY_SECRET') { "" } %>
  bucket: <%= ENV.fetch('ALIYUN_BUCKET') { "paul-dev" } %>
  endpoint: <%= ENV.fetch('ALIYUN_ENDPOINT') { "oss-cn-beijing.aliyuncs.com" } %>
  # path prefix, default: /
  path: "paul"
  # Bucket public: true/false, default: true, for generate public/private URL.
  public: false

test:
  service: Aliyun
  access_key_id: <%= ENV.fetch('ALIYUN_ACCESS_KEY_ID') { "" } %>
  access_key_secret: <%= ENV.fetch('ALIYUN_ACCESS_KEY_SECRET') { "" } %>
  bucket: <%= ENV.fetch('ALIYUN_BUCKET') { "paul-test" } %>
  endpoint: <%= ENV.fetch('ALIYUN_ENDPOINT') { "oss-cn-beijing.aliyuncs.com" } %>
  # path prefix, default: /
  path: "paul"
  # Bucket public: true/false, default: true, for generate public/private URL.
  public: false

production:
  service: Aliyun
  access_key_id: <%= ENV.fetch('ALIYUN_ACCESS_KEY_ID') { "" } %>
  access_key_secret: <%= ENV.fetch('ALIYUN_ACCESS_KEY_SECRET') { "" } %>
  bucket: <%= ENV.fetch('ALIYUN_BUCKET') { "paul-prod" } %>
  endpoint: <%= ENV.fetch('ALIYUN_ENDPOINT') { "oss-cn-beijing.aliyuncs.com" } %>
  # path prefix, default: /
  path: "paul"
  # Bucket public: true/false, default: true, for generate public/private URL.
  public: false

# Use rails credentials:edit to set the AWS secrets (as aws:access_key_id|secret_access_key)
# amazon:
#   service: S3
#   access_key_id: <%= Rails.application.credentials.dig(:aws, :access_key_id) %>
#   secret_access_key: <%= Rails.application.credentials.dig(:aws, :secret_access_key) %>
#   region: us-east-1
#   bucket: your_own_bucket

# Remember not to checkin your GCS keyfile to a repository
# google:
#   service: GCS
#   project: your_project
#   credentials: <%= Rails.root.join("path/to/gcs.keyfile") %>
#   bucket: your_own_bucket

# Use rails credentials:edit to set the Azure Storage secret (as azure_storage:storage_access_key)
# microsoft:
#   service: AzureStorage
#   storage_account_name: your_account_name
#   storage_access_key: <%= Rails.application.credentials.dig(:azure_storage, :storage_access_key) %>
#   container: your_container_name

# mirror:
#   service: Mirror
#   primary: local
#   mirrors: [ amazon, google, microsoft ]
